# Generated by Django 5.0.4 on 2024-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='needs_update',
            field=models.BooleanField(default=True),
        ),
    ]
