# Generated by Django 5.0.4 on 2024-05-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_financialreport_needs_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='needs_update',
        ),
    ]
