# Generated by Django 5.0.4 on 2024-07-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_rename_planned_amount_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='donor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='purpose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
