# Generated by Django 5.0.4 on 2024-07-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_income_contact_info_income_created_at_income_donor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='contact_info',
            new_name='contact',
        ),
    ]
