# Generated by Django 5.0.4 on 2024-07-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_rename_contact_info_income_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='updated_at',
        ),
    ]
