# Generated by Django 5.0.4 on 2024-07-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_remove_income_created_at_remove_income_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='contact',
        ),
       
    ]
