# Generated by Django 5.0.4 on 2024-07-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
