# Generated by Django 5.0.4 on 2024-07-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_rename_contact_info_servicerequest_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='contact_info',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='acknowledgement',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='notes',
        ),
    ]
