# Generated by Django 5.0.4 on 2024-07-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_rename_contact_info_donation_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='contact',
            new_name='contact_field',
        ),
    ]
