# Generated by Django 5.0.4 on 2024-07-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_remove_donation_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='contact_field',
            new_name='contact',
        ),
    ]
