# Generated by Django 5.0.4 on 2024-07-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_rename_contact_field_donation_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
