# Generated by Django 5.0.4 on 2024-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_donation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='contact',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='purpose',
            new_name='description',
        ),
    ]
