export const ANNOUNCEMENT_DETAILS_REQUEST = "ANNOUNCEMENT_DETAILS_REQUEST"
export const ANNOUNCEMENT_DETAILS_SUCCESS = "ANNOUNCEMENT_DETAILS_SUCCESS"
export const ANNOUNCEMENT_DETAILS_FAIL = "ANNOUNCEMENT_DETAILS_FAIL"
export const ANNOUNCEMENT_UPDATE_FAIL = "ANNOUNCEMENT_UPDATE_FAIL"
export const ANNOUNCEMENT_UPDATE_SUCCESS = "ANNOUNCEMENT_UPDATE_SUCCESS"
export const ANNOUNCEMENT_UPDATE_REQUEST = "ANNOUNCEMENT_UPDATE_REQUEST"


