export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST"
export const ANNOUNCEMENT_LIST_SUCCESS = "ANNOUNCEMENT_LIST_SUCCESS"
export const ANNOUNCEMENT_LIST_FAIL = "ANNOUNCEMENT_LIST_FAIL"