export const FETCH_DONATION_REQUEST = 'FETCH_DONATION_REQUEST'
export const FETCH_DONATION_SUCCESS = 'FETCH_DONATION_SUCCESS'
export const FETCH_DONATION_FAIL = 'FETCH_DONATION_FAIL'

export const ADD_DONATION_REQUEST = 'ADD_DONATION_REQUEST'
export const ADD_DONATION_SUCCESS = 'ADD_DONATION_SUCCESS'
export const ADD_DONATION_FAIL = 'ADD_DONATION_FAIL'

export const PROCESS_DONATION_REQUEST = "PROCESS_DONATION_REQUEST";
export const PROCESS_DONATION_SUCCESS = "PROCESS_DONATION_SUCCESS";
export const PROCESS_DONATION_FAILURE = "PROCESS_DONATION_FAILURE";

export const DONATION_REQUEST_INITIAL = "DONATION_REQUEST_INITIAL";
export const DONATION_REQUEST_SUCCESS = "DONATION_REQUEST_SUCCESS";
export const DONATION_REQUEST_FAILURE = "DONATION_REQUEST_FAILUR";
