export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";export const ANNOUNCEMENT_UPDATE_FAIL = "ANNOUNCEMENT_UPDATE_FAIL"
export const EVENT_UPDATE_SUCCESS = "EVENT_UPDATE_SUCCESS"
export const EVENT_UPDATE_REQUEST = "EVENT_UPDATE_REQUEST"
export const EVENT_UPDATE_FAIL  = "EVENT_UPDATE_FAIL "