// src/constants/financialConstants.js
export const FETCH_FINANCIAL_DATA_REQUEST = 'FETCH_FINANCIAL_DATA_REQUEST';
export const FETCH_FINANCIAL_DATA_SUCCESS = 'FETCH_FINANCIAL_DATA_SUCCESS';
export const FETCH_FINANCIAL_DATA_FAILURE = 'FETCH_FINANCIAL_DATA_FAILURE';
