// src/constants/incomeConstants.js
export const FETCH_INCOME_REQUEST = 'FETCH_INCOME_REQUEST';
export const FETCH_INCOME_SUCCESS = 'FETCH_INCOME_SUCCESS';
export const FETCH_INCOME_FAILURE = 'FETCH_INCOME_FAILURE';
export const ADD_INCOME_REQUEST = 'ADD_INCOME_REQUEST';
export const ADD_INCOME_SUCCESS = 'ADD_INCOME_SUCCESS';
export const ADD_INCOME_FAILURE = 'ADD_INCOME_FAILURE';
export const SET_NEW_INCOME= 'SET_NEW_INCOME';
export const RESET_NEW_INCOME= 'RESET_NEW_INCOME';


