export const FETCH_FINANCIAL_REPORT_REQUEST = 'FETCH_FINANCIAL_REPORT_REQUEST';
export const FETCH_FINANCIAL_REPORT_SUCCESS = 'FETCH_FINANCIAL_REPORT_SUCCESS';
export const FETCH_FINANCIAL_REPORT_FAILURE = 'FETCH_FINANCIAL_REPORT_FAILURE';